### ISSUE TITLE
KeyError: '/boot'

### ISSUE THREAD

**Issue by amerello** [corvusmod/decive_hexxa_atenea#2]
When trying to build this with 
```
lunch cm_atenea-userdebug && mka bacon
```
I'm getting the following error
```
Package target files: /home/developer/cyanogenmod/out/target/product/atenea/obj/PACKAGING/target_files_intermediates/cm_atenea-target_files-55be84319f.zip
using prebuilt recovery.img from BOOTABLE_IMAGES...
using prebuilt boot.img from BOOTABLE_IMAGES...
Traceback (most recent call last):
  File "./build/tools/releasetools/make_recovery_patch", line 53, in <module>
    main(sys.argv[1:])
  File "./build/tools/releasetools/make_recovery_patch", line 49, in main
    common.MakeRecoveryPatch(input_dir, output_sink, recovery_img, boot_img)
  File "/home/developer/cyanogenmod/build/tools/releasetools/common.py", line 1289, in MakeRecoveryPatch
    td_pair = GetTypeAndDevice("/boot", info_dict)
  File "/home/developer/cyanogenmod/build/tools/releasetools/common.py", line 1240, in GetTypeAndDevice
    return PARTITION_TYPES[fstab[mount_point].fs_type], fstab[mount_point].device
KeyError: '/boot'
build/core/Makefile:1498: recipe for target '/home/developer/cyanogenmod/out/target/product/atenea/obj/PACKAGING/target_files_intermediates/cm_atenea-target_files-55be84319f.zip' failed
make: *** [/home/developer/cyanogenmod/out/target/product/atenea/obj/PACKAGING/target_files_intermediates/cm_atenea-target_files-55be84319f.zip] Error 1
make: Leaving directory '/home/developer/cyanogenmod'
```
I suppose I need to introduce some modifications on `device/hexxa/atenea/rootdir/recovery.fstab` but I'm not sure what.

NOTE: I had to merge `system/core` and `frameworks/base` back from cyano 12.1, which I did on https://github.com/amerello/android

**Comment by MLXProjects** [comment]
KeyError in Python means that you tried to access something that isn't available in a list.
I think it's caused by /boot not being declared in the recovery.fstab, not sure tho. I'll try to make this compile.
btw it's nice to develop for a 6 y/o device :D

**Comment by MLXProjects** [comment]
Already fixed on pull request #3, now it's buildable.
Had to fix partitions naming too (check my fork at 2nd commit), but may not be needed given my weird testing environment :P
I was able to build it using official cm12.1 source and patches from here: 
https://github.com/Deepflex/android_device_elephone_p6000_pro_cm12_1/tree/master/patches/frameworks_base
